"""Core data models for the trading system."""

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Optional


class Side(Enum):
    BUY = "BUY"
    SELL = "SELL"


class OrderStatus(Enum):
    PENDING = "PENDING"
    FILLED = "FILLED"
    CANCELLED = "CANCELLED"


@dataclass
class Order:
    symbol: str
    side: Side
    quantity: float
    price: float
    timestamp: datetime
    status: OrderStatus = OrderStatus.PENDING
    fill_price: Optional[float] = None
    commission: float = 0.0

    @property
    def cost(self) -> float:
        price = self.fill_price if self.fill_price else self.price
        return price * self.quantity + self.commission


@dataclass
class Position:
    symbol: str
    quantity: float
    avg_entry_price: float
    current_price: float = 0.0

    @property
    def market_value(self) -> float:
        return self.quantity * self.current_price

    @property
    def unrealized_pnl(self) -> float:
        return (self.current_price - self.avg_entry_price) * self.quantity

    @property
    def unrealized_pnl_pct(self) -> float:
        if self.avg_entry_price == 0:
            return 0.0
        return (self.current_price - self.avg_entry_price) / self.avg_entry_price


@dataclass
class Trade:
    symbol: str
    side: Side
    quantity: float
    entry_price: float
    exit_price: float
    entry_time: datetime
    exit_time: datetime
    commission: float = 0.0

    @property
    def pnl(self) -> float:
        if self.side == Side.BUY:
            gross = (self.exit_price - self.entry_price) * self.quantity
        else:
            gross = (self.entry_price - self.exit_price) * self.quantity
        return gross - self.commission

    @property
    def pnl_pct(self) -> float:
        if self.entry_price == 0:
            return 0.0
        return self.pnl / (self.entry_price * self.quantity)

    @property
    def holding_period(self):
        return self.exit_time - self.entry_time


@dataclass
class Signal:
    """A trading signal generated by a strategy."""
    symbol: str
    side: Side
    strength: float  # 0.0 to 1.0
    timestamp: datetime
    reason: str = ""
